### ISSUE TITLE
Setting Method to Token Payment during initial Transaction?

### ISSUE THREAD

**Issue by brocktimus** [eWAYPayment/eway-rapid-ruby#3]
Reading API docs (https://eway.io/api-v3/?ruby#token-payments) today it indicated that it should be possible to create and charge a customer token at the same time by using a combination of the Rapid SDK + Responsive Shared Page (amongst other options) and setting the Transaction Method.

I'm mocking out the code now to do this since it's something we'd like to do. 

I found the `EwayRapid::Enums::TOKEN_PAYMENT` which corresponded to the Transaction Method we'd wanted. This doesn't seem to be used anywhere in the code from what I can see. Digging through more code when we're using `create_transaction` with `Enums::PaymentMethod::RESPONSIVE_SHARED` we end up in `Message::TransactionProcess::TransResponsiveSharedMsgProcess` which converts the input transaction into a request via `Convert::Request::TransactionToCreateAccessCodeSharedRequest`. 

This last one sets the Transaction Method, but only ever to `PROCESS_PAYMENT` or `AUTHORISE`. After which it just gets a response and then converted.

So being able to set this to `TOKEN_PAYMENT` in the ruby SDK would be fantastic.

Other thing is I'm tempted to just override or monkey patch it for my use :stuck_out_tongue:. But if I'm doing so I may as well do it so that I can create a pull request. Writing this up I think I'll just do an `attr_accessor` on `Transaction` with a method variable. If it is set then that gets put onto the request, if it isn't then it defaults to the current logic.

That MAINLY relies on the response + result interpreters being able to interpret the different content. But I think I'll just open a PR since the initial bit sounds simple enough.

**Comment by brocktimus** [comment]
I'm not sure based on API. But having the SaveCustomer setting on transaction might have been the intention for this? That doesn't seem to be in the Ruby API though.

**Comment by incarnate** [comment]
Good timing, I was just writing a reply to this.

Yes, in some of the SDKs we have the "SaveCustomer" flag in Transaction to handle this situation. This then toggles the `Method` at the appropriate time (see the example in the [PHP SDK here](https://github.com/eWAYPayment/eway-rapid-php/blob/master/src/Rapid/Client.php#L335)).

 But this flag hasn't been ported to the Ruby SDK yet, sorry about that!

**Comment by brocktimus** [comment]
I'll just port that logic over. Seems simple enough.

**Comment by incarnate** [comment]
This change has been included with the 2.0.0 release, thank you very much! Merry Christmas!
